# tools/report/export_tool.py
import json
import os
from pathlib import Path
from crewai.tools import tool


@tool("Export Report to HTML and PDF")
def export_report(input_json: str) -> str:
    """
    Xuất báo cáo Markdown thành HTML và PDF.
    Input: JSON string {"markdown_content": "...", "output_dir": "./outputs/reports"}
    hoặc JSON với "report_path" để đọc từ file.
    """
    try:
        params = json.loads(input_json)
        markdown_content = params.get("markdown_content")
        report_path = params.get("report_path")
        output_dir = params.get("output_dir", "outputs/reports")
    except Exception:
        # Treat as markdown content directly
        markdown_content = input_json
        output_dir = "outputs/reports"
        report_path = None

    os.makedirs(output_dir, exist_ok=True)

    # Read from file if path provided
    if report_path and not markdown_content:
        try:
            with open(report_path, "r", encoding="utf-8") as f:
                markdown_content = f.read()
        except Exception as e:
            return json.dumps({"error": f"Could not read report file: {e}"})

    if not markdown_content:
        # Try default path
        default_path = os.path.join(output_dir, "attack_surface_report.md")
        if os.path.exists(default_path):
            with open(default_path, "r", encoding="utf-8") as f:
                markdown_content = f.read()
        else:
            return json.dumps({"error": "No markdown content provided and no report file found"})

    html_path = os.path.join(output_dir, "attack_surface_report.html")
    pdf_path = os.path.join(output_dir, "attack_surface_report.pdf")

    results = {
        "markdown_saved": False,
        "html_exported": False,
        "pdf_exported": False,
        "files": {},
        "errors": [],
    }

    # Save/update markdown
    md_path = os.path.join(output_dir, "attack_surface_report.md")
    try:
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(markdown_content)
        results["markdown_saved"] = True
        results["files"]["markdown"] = md_path
    except Exception as e:
        results["errors"].append(f"Markdown save error: {e}")

    # Convert to HTML
    html_body = ""  # initialized here so PDF fallback can always reference it
    try:
        import markdown2
        html_body = markdown2.markdown(
            markdown_content,
            extras=["tables", "fenced-code-blocks", "header-ids", "strike"]
        )

        html_full = f"""<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attack Surface Assessment Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Arial, sans-serif;
            background: #0a0e1a;
            color: #c9d1d9;
            max-width: 1100px;
            margin: 40px auto;
            padding: 20px 40px;
            line-height: 1.7;
        }}
        h1 {{ color: #58a6ff; border-bottom: 2px solid #21262d; padding-bottom: 10px; }}
        h2 {{ color: #79c0ff; border-bottom: 1px solid #21262d; padding-bottom: 5px; margin-top: 40px; }}
        h3 {{ color: #a5d6ff; }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
            font-size: 14px;
        }}
        th {{
            background: #161b22;
            border: 1px solid #30363d;
            padding: 10px 14px;
            text-align: left;
            color: #58a6ff;
        }}
        td {{
            border: 1px solid #21262d;
            padding: 8px 14px;
        }}
        tr:nth-child(even) {{ background: #0d1117; }}
        tr:hover {{ background: #1c2128; }}
        code {{
            background: #161b22;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
            color: #ff7b72;
        }}
        pre {{
            background: #0d1117;
            border: 1px solid #30363d;
            border-radius: 6px;
            padding: 16px;
            overflow-x: auto;
        }}
        pre code {{ background: none; color: #a5d6ff; }}
        blockquote {{
            border-left: 4px solid #3b82f6;
            margin: 0;
            padding: 8px 16px;
            background: #0d1117;
            color: #8b949e;
        }}
        .severity-critical {{ color: #ff4444; font-weight: bold; }}
        .severity-high {{ color: #ff8800; font-weight: bold; }}
        .severity-medium {{ color: #ffcc00; }}
        .severity-low {{ color: #4488ff; }}
        hr {{ border-color: #21262d; }}
        a {{ color: #58a6ff; }}
        .footer {{
            margin-top: 60px;
            padding-top: 20px;
            border-top: 1px solid #21262d;
            color: #6e7681;
            font-size: 12px;
            text-align: center;
        }}
    </style>
</head>
<body>
{html_body}
<div class="footer">
    <p>Generated by Multi-Agent Recon System | CrewAI + DeepSeek</p>
</div>
</body>
</html>"""

        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_full)

        results["html_exported"] = True
        results["files"]["html"] = html_path

    except ImportError:
        results["errors"].append("markdown2 not installed. Run: pip install markdown2")
    except Exception as e:
        results["errors"].append(f"HTML export error: {e}")

    # Convert to PDF
    try:
        from weasyprint import HTML, CSS
        if os.path.exists(html_path):
            HTML(filename=html_path).write_pdf(pdf_path)
            results["pdf_exported"] = True
            results["files"]["pdf"] = pdf_path
        else:
            results["errors"].append("HTML file not found for PDF conversion")
    except (ImportError, OSError, Exception) as _weasy_err:
        # WeasyPrint requires libgobject/pango (Linux/macOS GTK). On Windows,
        # fall back to xhtml2pdf which is pure-Python.
        try:
            from xhtml2pdf import pisa  # type: ignore

            # Register a system TTF font that supports Vietnamese characters.
            # xhtml2pdf uses reportlab internally — register the font there.
            _font_registered = False
            try:
                from reportlab.pdfbase import pdfmetrics
                from reportlab.pdfbase.ttfonts import TTFont
                import sys

                # Candidate fonts (Windows → Linux → macOS fallbacks)
                _font_candidates = [
                    ("C:/Windows/Fonts/arial.ttf", "C:/Windows/Fonts/arialbd.ttf",
                     "C:/Windows/Fonts/ariali.ttf", "C:/Windows/Fonts/arialbi.ttf"),
                ]
                if sys.platform != "win32":
                    _font_candidates.append(
                        ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
                         "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
                         "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf",
                         "/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf"),
                    )

                for regular, bold, italic, bolditalic in _font_candidates:
                    if os.path.exists(regular):
                        pdfmetrics.registerFont(TTFont("UniFont", regular))
                        if os.path.exists(bold):
                            pdfmetrics.registerFont(TTFont("UniFont-Bold", bold))
                        if os.path.exists(italic):
                            pdfmetrics.registerFont(TTFont("UniFont-Italic", italic))
                        if os.path.exists(bolditalic):
                            pdfmetrics.registerFont(TTFont("UniFont-BoldItalic", bolditalic))

                        from reportlab.lib.fonts import addMapping
                        addMapping("UniFont", 0, 0, "UniFont")        # normal
                        addMapping("UniFont", 1, 0, "UniFont-Bold")   # bold
                        addMapping("UniFont", 0, 1, "UniFont-Italic") # italic
                        addMapping("UniFont", 1, 1, "UniFont-BoldItalic")  # bold-italic

                        _font_registered = True
                        break
            except Exception:
                pass

            # Build font-family CSS based on whether registration succeeded
            _font_family = "'UniFont', Arial, sans-serif" if _font_registered else "Arial, sans-serif"

            # xhtml2pdf renders from HTML source — use a simplified light CSS
            # version of the report (dark backgrounds don't print well anyway)
            # xhtml2pdf does NOT support CSS nth-child or complex selectors.
            # Keep CSS minimal; use only element selectors.
            light_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<style>
  body {{ font-family: {_font_family}; font-size: 11pt; color: #111; margin: 2cm; }}
  h1 {{ color: #003580; font-size: 18pt; }}
  h2 {{ color: #003580; font-size: 14pt; border-bottom: 1pt solid #ccc; }}
  h3 {{ color: #222; font-size: 12pt; }}
  table {{ border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 10pt; }}
  th {{ background: #003580; color: #fff; border: 1pt solid #aaa; padding: 4pt; }}
  td {{ border: 1pt solid #ccc; padding: 4pt; }}
  code {{ background: #f0f0f0; padding: 1pt 3pt; font-size: 9pt; }}
  pre {{ background: #f0f0f0; padding: 6pt; font-size: 9pt; }}
</style>
</head>
<body>
{html_body}
</body>
</html>"""
            import io as _io
            with open(pdf_path, "wb") as pdf_file:
                pisa_status = pisa.CreatePDF(
                    _io.StringIO(light_html), dest=pdf_file, encoding="utf-8"
                )
            if not pisa_status.err:
                results["pdf_exported"] = True
                results["files"]["pdf"] = pdf_path
            else:
                results["errors"].append(f"xhtml2pdf render error (code {pisa_status.err})")
        except ImportError:
            results["errors"].append(
                "PDF export unavailable: install xhtml2pdf (pip install xhtml2pdf) "
                "or weasyprint with GTK libraries."
            )
        except Exception as xpdf_err:
            results["errors"].append(f"xhtml2pdf error: {xpdf_err}")

    results["summary"] = (
        f"Export complete: "
        f"MD={'✓' if results['markdown_saved'] else '✗'}, "
        f"HTML={'✓' if results['html_exported'] else '✗'}, "
        f"PDF={'✓' if results['pdf_exported'] else '✗'}"
    )

    return json.dumps(results, ensure_ascii=False, indent=2)
