# tools/active/waf_tool.py
import json
import requests
from crewai.tools import tool

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "server:cloudflare"],
        "cookies": ["__cfduid", "__cfuid", "cf_clearance"],
        "body": ["cloudflare", "cf-ray"],
    },
    "AWS WAF / CloudFront": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-cache:hit from cloudfront"],
        "cookies": [],
        "body": ["aws", "cloudfront"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-check-cacheable", "akamai-cache-status"],
        "cookies": ["akacd_"],
        "body": [],
    },
    "Imperva/Incapsula": {
        "headers": ["x-cdn:incapsula", "x-iinfo"],
        "cookies": ["incap_ses_", "visid_incap"],
        "body": ["incapsula", "incap_ses"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "cookies": ["TS"],
        "body": [],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache", "server:sucuri"],
        "cookies": [],
        "body": ["sucuri", "cloudproxy"],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "cookies": ["barra_counter_session"],
        "body": ["barracuda"],
    },
    "ModSecurity": {
        "headers": ["server:mod_security", "x-mod-security"],
        "cookies": [],
        "body": ["modsecurity", "mod_security", "NOYB"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": [],
        "body": ["generated by wordfence", "wordfence"],
    },
}

_HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}


@tool("WAF Detector")
def waf_detector(url: str) -> str:
    """
    Phát hiện Web Application Firewall (WAF) qua header/cookie/body fingerprinting.
    Hữu ích để điều chỉnh scan strategy và đánh giá phòng thủ.
    Input: URL hoặc domain (ví dụ: https://example.com)
    """
    from tools.active.http_helper import normalize_url, smart_request
    url = normalize_url(url)

    results = {
        "url": url,
        "waf_detected": False,
        "waf_product": None,
        "confidence": "None",
        "evidence": [],
        "bypass_suggestions": [],
    }

    try:
        # Normal request
        resp_normal = smart_request(url, timeout=15, headers=_HEADERS)
        normal_headers = {k.lower(): v.lower() for k, v in resp_normal.headers.items()}
        normal_cookies = {k.lower(): v.lower() for k, v in resp_normal.cookies.items()}
        normal_body = resp_normal.text[:5000].lower()

        # Attack simulation request (strip existing query string to avoid double '?')
        attack_url = resp_normal.url.split("?")[0] + "?id=1+AND+1=1--"
        try:
            resp_attack = requests.get(attack_url, headers=_HEADERS, timeout=15,
                                       allow_redirects=True, verify=False)
            attack_headers = {k.lower(): v.lower() for k, v in resp_attack.headers.items()}
            attack_body = resp_attack.text[:5000].lower()
        except Exception:
            attack_headers = {}
            attack_body = ""

        for waf_name, sig in WAF_SIGNATURES.items():
            evidence = []

            # Check headers
            for hdr_sig in sig["headers"]:
                if ":" in hdr_sig:
                    h_name, h_val = hdr_sig.split(":", 1)
                    if h_name in normal_headers and h_val in normal_headers[h_name]:
                        evidence.append(f"Header {hdr_sig} found")
                    if h_name in attack_headers and h_val in attack_headers[h_name]:
                        evidence.append(f"Attack response header {hdr_sig} found")
                else:
                    if hdr_sig in normal_headers:
                        evidence.append(f"Header '{hdr_sig}' present")

            # Check cookies
            for ck in sig["cookies"]:
                for cookie_name in normal_cookies:
                    if ck.lower() in cookie_name:
                        evidence.append(f"Cookie '{cookie_name}' matched pattern '{ck}'")

            # Check body
            for bdy in sig["body"]:
                if bdy in normal_body or bdy in attack_body:
                    evidence.append(f"Body contains '{bdy}'")

            if evidence:
                results["waf_detected"] = True
                results["waf_product"] = waf_name
                results["evidence"] = evidence
                results["confidence"] = "High" if len(evidence) >= 2 else "Medium"
                results["bypass_suggestions"] = [
                    "Use case variation in payloads",
                    "Encode payload with URL/HTML encoding",
                    "Add whitespace between operators",
                    "Switch to uncommon HTTP methods",
                ]
                break

        # Generic WAF detection by status code
        if not results["waf_detected"]:
            if resp_normal.status_code in (406, 429, 503, 999):
                results["waf_detected"] = True
                results["waf_product"] = "Unknown WAF"
                results["confidence"] = "Low"
                results["evidence"] = [f"Attack response code: {resp_normal.status_code}"]

    except Exception as e:
        results["error"] = str(e)

    return json.dumps(results, ensure_ascii=False, indent=2)
